export const CREATE_SHIPMENT = "CREATE_SHIPMENT";
export const RETRIEVE_SHIPMENTS = "RETRIEVE_SHIPMENTS";
export const UPDATE_SHIPMENT = "UPDATE_SHIPMENT";
export const DELETE_SHIPMENT = "DELETE_SHIPMENT";
export const DELETE_ALL_SHIPMENTS = "DELETE_ALL_SHIPMENTS";